#!/usr/bin/env python

from MEGAN.blast2lca import Blast2lca
from MEGAN.process import Parser
import argparse

class DAA2combined:
    def __init__(self, rootDir, sampleDir, sampleName, inputFile, taxOutput, koOutput, blast2lca = '/export2/home/uesu/local/megan6ce/tools/blast2lca', gi2taxid  = '/export2/home/uesu/simulation_fr_the_beginning/data/classifier/gi2taxid.refseq.map', gi2kegg   = '/export2/home/uesu/github/MEGAN/tools/gi2kegg.map', new=False):
        self.rootDir    = rootDir
        self.sampleDir  = sampleDir
        self.sampleName = sampleName
        self.inputFile  = inputFile
        self.taxOutput  = taxOutput
        self.koOutput   = koOutput
        self.script     = blast2lca
        self.gi2taxid   = gi2taxid
        self.gi2kegg    = gi2kegg
        self.new  = new
        self.run()

    def run(self):
        b2l = Blast2lca(self.script, self.gi2kegg, self.gi2taxid)
        b2l.run(self.rootDir, self.sampleDir, self.inputFile, self.taxOutput, self.koOutput)
        lcaparser = Parser(self.rootDir, self.sampleDir, self.sampleName, self.taxOutput, self.koOutput)
        lcaparser.combined()
        lcaparser.LCA2neo4j()

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Command line wrapper of blast2lca and merging annotations')

    parser.add_argument('rootDir', metavar='root', type=str,
                        help="the root directory")

    parser.add_argument('sampleDir', metavar='sampledir', type=str,
                        help="relative path from root directory to sample directory")

    parser.add_argument('sampleName', metavar='sample', type=str,
                        help="sample name, could be same name as sample directory. for combined ko and taxon")

    parser.add_argument('input', metavar='input file', type=str,
                        help="could be DAA (.daa) or blast (.m8)")

    parser.add_argument('tax', metavar='taxonomy', type=str,
                        help='blast2lca taxonomy output filename - has to be in taxIDs d__2')

    parser.add_argument('ko', metavar='kegg', type=str,
                        help='blast2lca ko output filename')

    parser.add_argument('--new', dest='newNR', action='store_true',
                        help='')
    parser.add_argument('--blast2lca', dest='script', default='/export2/home/uesu/local/megan6ce/tools/blast2lca',
                        help='blast2lca script')
    parser.add_argument('--gi2kegg', dest='gi2kegg', default='/export2/home/uesu/github/MEGAN/tools/gi2kegg.map',
                        help='gi2kegg mapping file')
    parser.add_argument('--gi2taxid', dest='gi2taxid', default='/export2/home/uesu/simulation_fr_the_beginning/data/classifier/gi2taxid.refseq.map',
                        help='gi2taxid mapping file')
    parser.add_argument('--debug', dest='debug', action='store_true',
                        help='debug mode')
    parser.add_argument('--verbose', dest='verbose', action='store_true',
                        help='to switch on verbose mode')

    args = parser.parse_args()
    DAA2combined(args.rootDir, args.sampleDir, args.sampleName, args.input, args.tax, args.ko, args.script,args.gi2taxid, args.gi2kegg, args.newNR)
