#!/usr/bin/env python

from MEGAN.blast2lca import Blast2lca
import fire

class DAA2combined:
    def __init__(self, rootDir, sampleDir, sampleName, inputFile, taxOutput, koOutput, blast2lca = '/export2/home/uesu/local/megan6ce/tools/blast2lca', gi2taxid  = '/export2/home/uesu/simulation_fr_the_beginning/data/classifier/gi2taxid.refseq.map', gi2kegg   = '/export2/home/uesu/github/MEGAN/tools/gi2kegg.map'):
        self.rootDir    = rootDir
        self.sampleDir  = sampleDir
        self.sampleName = sampleName
        self.inputFile  = inputFile
        self.taxOutput  = taxOutput
        self.koOutput   = koOutput
        self.script     = blast2lca
        self.gi2taxid   = gi2taxid
        self.gi2kegg    = gi2kegg
        self.run()

    def run(self):
        b2l = Blast2lca(self.script, self.gi2kegg, self.gi2taxid)
        b2l.run(self.rootDir, self.sampleDir, self.inputFile, self.taxOutput, self.koOutput)

if __name__ == '__main__':
    fire.Fire(DAA2combined)
